### PR TITLE
Add MainController with / route and add main.vtl with placeholder text

### PR DESCRIPTION
**Pull request by stewartpaul22**
MainController and main.vtl have been added on the feature/mainController branch.

layout.vtl has been updated on the feature/layout branch.

These two branches need to be merged so that the overall functionality can be tested.

### CODE REVIEW

**Comment by stewartpaul22** [comment]
These two feature branches have been merged locally.  They have been tested and are up-to-date on origin, so are ready to be merged together then merged in to develop.

**Review by riakoronidi — COMMENTED** [review]
Hi Paul, you have added a pull request to merge your code FROM feature/mainController TO master, you skipped develop - just putting a comment here as a wee reminder

**Comment by stewartpaul22** [comment]
Good find Ria.  I will close this pull request then open a new one with the request to merge to develop.

**Comment by stewartpaul22** [comment]
Branch closed without any merge.

**Pull request closed without merging**
